name: zeronet_ws
description: ZeroNet WebSocket Package.
version: 0.0.4
homepage: https://github.com/canewsin/zeronet_ws

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  web_socket_channel: ^2.1.0

dev_dependencies:
  test:
